// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Branch(arg1:string):Promise<string>;

export function DiffStat(arg1:string):Promise<string>;

export function Status(arg1:string):Promise<string>;
