// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function Run(arg1:string,arg2:string,arg3:Array<string>,arg4:string,arg5:number):Promise<app.ProcessOutput>;
