// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Run(arg1:string,arg2:Array<string>,arg3:string,arg4:number):Promise<app.ProcessOutput>;
