// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Changes(arg1:string,arg2:string):Promise<Array<app.FileChange>>;

export function Copy(arg1:string):Promise<app.SandboxInfo>;

export function Merge(arg1:string,arg2:string,arg3:Array<string>):Promise<number>;

export function Remove(arg1:string):Promise<void>;
