// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1) {
  return window['go']['app']['Updater']['ApplyUpdate'](arg1);
}

export function CheckUpdate() {
  return window['go']['app']['Updater']['CheckUpdate']();
}

export function DownloadUpdate() {
  return window['go']['app']['Updater']['DownloadUpdate']();
}

export function Restart() {
  return window['go']['app']['Updater']['Restart']();
}
