// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeletePath(arg1:string):Promise<void>;

export function HomeDir():Promise<string>;

export function ListDir(arg1:string):Promise<Array<main.DirItem>>;

export function ReadText(arg1:string):Promise<any>;

export function WriteText(arg1:string,arg2:string):Promise<void>;
