// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePath(arg1) {
  return window['go']['main']['Fs']['DeletePath'](arg1);
}

export function HomeDir() {
  return window['go']['main']['Fs']['HomeDir']();
}

export function ListDir(arg1) {
  return window['go']['main']['Fs']['ListDir'](arg1);
}

export function ReadText(arg1) {
  return window['go']['main']['Fs']['ReadText'](arg1);
}

export function WriteText(arg1, arg2) {
  return window['go']['main']['Fs']['WriteText'](arg1, arg2);
}
