// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Branch(arg1) {
  return window['go']['main']['Git']['Branch'](arg1);
}

export function DiffStat(arg1) {
  return window['go']['main']['Git']['DiffStat'](arg1);
}

export function Status(arg1) {
  return window['go']['main']['Git']['Status'](arg1);
}
