// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function KillPTY(arg1:string):Promise<void>;

export function OpenPTY(arg1:string,arg2:number,arg3:number):Promise<string>;

export function ResizePTY(arg1:string,arg2:number,arg3:number):Promise<void>;

export function WritePTY(arg1:string,arg2:string):Promise<void>;
