// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PtyKill(arg1:string):Promise<void>;

export function PtyResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PtySpawn(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string,arg6:Array<string>):Promise<string>;

export function PtyWrite(arg1:string,arg2:string):Promise<void>;
