// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function KillPTY(arg1) {
  return window['go']['main']['Pty']['KillPTY'](arg1);
}

export function OpenPTY(arg1, arg2, arg3) {
  return window['go']['main']['Pty']['OpenPTY'](arg1, arg2, arg3);
}

export function ResizePTY(arg1, arg2, arg3) {
  return window['go']['main']['Pty']['ResizePTY'](arg1, arg2, arg3);
}

export function WritePTY(arg1, arg2) {
  return window['go']['main']['Pty']['WritePTY'](arg1, arg2);
}
