// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PtyKill(arg1) {
  return window['go']['main']['Pty']['PtyKill'](arg1);
}

export function PtyResize(arg1, arg2, arg3) {
  return window['go']['main']['Pty']['PtyResize'](arg1, arg2, arg3);
}

export function PtySpawn(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['Pty']['PtySpawn'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PtyWrite(arg1, arg2) {
  return window['go']['main']['Pty']['PtyWrite'](arg1, arg2);
}
