// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Changes(arg1, arg2) {
  return window['go']['main']['Sandbox']['Changes'](arg1, arg2);
}

export function Copy(arg1) {
  return window['go']['main']['Sandbox']['Copy'](arg1);
}

export function Merge(arg1, arg2, arg3) {
  return window['go']['main']['Sandbox']['Merge'](arg1, arg2, arg3);
}

export function Remove(arg1) {
  return window['go']['main']['Sandbox']['Remove'](arg1);
}
