// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ask(arg1:string,arg2:string):Promise<boolean>;

export function ClipboardGetText():Promise<string>;

export function ClipboardSetText(arg1:string):Promise<void>;

export function DetectBins(arg1:Array<string>):Promise<Array<string>>;

export function FindEditors():Promise<Array<string>>;

export function OpenDialog(arg1:string,arg2:boolean):Promise<string>;

export function OpenIn(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ResolveBash():Promise<string>;

export function SshHosts():Promise<Array<string>>;
