// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ask(arg1, arg2) {
  return window['go']['main']['Tools']['Ask'](arg1, arg2);
}

export function ClipboardGetText() {
  return window['go']['main']['Tools']['ClipboardGetText']();
}

export function ClipboardSetText(arg1) {
  return window['go']['main']['Tools']['ClipboardSetText'](arg1);
}

export function DetectBins(arg1) {
  return window['go']['main']['Tools']['DetectBins'](arg1);
}

export function FindEditors() {
  return window['go']['main']['Tools']['FindEditors']();
}

export function OpenDialog(arg1, arg2) {
  return window['go']['main']['Tools']['OpenDialog'](arg1, arg2);
}

export function OpenIn(arg1, arg2, arg3) {
  return window['go']['main']['Tools']['OpenIn'](arg1, arg2, arg3);
}

export function ResolveBash() {
  return window['go']['main']['Tools']['ResolveBash']();
}

export function SshHosts() {
  return window['go']['main']['Tools']['SshHosts']();
}
