// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyUpdate(arg1:string):Promise<void>;

export function CheckUpdate():Promise<main.UpdateRelease>;

export function DownloadUpdate():Promise<string>;

export function Restart():Promise<void>;
